# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('quality-of-services-example', ['quality-of-services'])
    obj.source = 'quality-of-services-example.cc'

