# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('quality-of-services', ['core'])
    module.source = [
    	 'model/quality-of-services.cc',
    	 'helper/quality-of-services-helper.cc',
    	 'model/filter-element.cc',
#        'model/diff-serv.cc',
#        'model/traffic-class.cc',
        ]

    module_test = bld.create_ns3_module_test_library('quality-of-services')
    module_test.source = [
#        'test/quality-of-services-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'quality-of-services'
    headers.source = [
        'model/quality-of-services.h',
        'helper/quality-of-services-helper.h',
        'model/diff-serv.h',
        'model/traffic-class.h',
        'model/filter.h',
        'model/filter-element.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

